### ISSUE TITLE
Documentation improvements - November 18, 2023

### ISSUE THREAD

**Issue by echarlesgrasby** [acrlabs/simkube#83]
## Description

In CONTRIBUTING.md, a reference URL to one of the pre-requisite tools (golangci-lint) takes the reader to the wrong link for the site. It directs the user to https://pre-commit.com/ rather than https://golangci-lint.run/

In README.md, there is a warning applicable to all project contributors. As a reader, I thought it would be helpful to include an emphasis around the warning to make it stand out to the reader. 

I have a submitted a PR to address both of these document changes here: https://github.com/acrlabs/simkube/pull/82

**Comment by drmorr0** [comment]
Merged, thanks for the fix!
